public class Judge {//[1]
    private enum Result {//[2]
        RESULT_WIN,//[3]
        RESULT_FALSE,//[4]
        RESULT_EVEN//[5]
    }
    private Shape myShape;//[6]
    private Shape yourShape;//[7]
    private Result result;//[8]
 
    public Judge (Shape yourShape, Shape myShape) {//[9]
        this.yourShape = yourShape;//[10]
        this.myShape = myShape;//[11]
        this.result = Result.RESULT_FALSE;//[12]
    }
    public void displayIntroduction() {//[20]
        Console.writeWithCR("じゃんけんを始めます。");//[21]
        Console.writeWithCR("G:ぐー，C:ちょき，P:ぱあ，それ以外:終わり");//[22]
        Console.writeWithCR("G/C/Pのどれかを選んで改行キーを押すと，じゃんけんが始まります。");//[23]
        Console.writeWithCR("じゃんけん");//[24]
    }
    public void sayCueWord() {//[40]
        switch (result) {//[41]
            case RESULT_WIN://[42]
            case RESULT_FALSE://[43]
                Console.write("ぽん！");//[44]
                break;//[45]
            case RESULT_EVEN://[46]
                Console.write("しょ");//[47]
                break;//[48]
        }
    }
    public void sayResult() {//[60]
        Console.write("　→　");//[61]
        Console.sleep(2);//[62]
        Console.write("あなたは" + yourShape.toString() + "　→　");//[63]
        Console.sleep(1);//[64]
        Console.writeWithCR("わたしは" + myShape.toString());//[65]
        switch (result) {//[66]
            case RESULT_WIN://[67]
                Console.writeWithCR("あなたの勝ち！");//[68]
                Console.writeWithCR("じゃんけん");//[69]
                break;//[70]
            case RESULT_FALSE://[71]
                Console.writeWithCR("あなたの負け！");//[72]
                Console.writeWithCR("じゃんけん");//[73]
                break;//[74]
            case RESULT_EVEN://[75]
                Console.writeWithCR("あいこで，");//[76]
                break;//[77]
        }
    }
    public void judge() {//[80]
        this.result = judgeByRule();//[81]
    }
    private Result judgeByRule() {//[82]
        if (yourShape.hand() == myShape.hand())//[83]
            return Result.RESULT_EVEN;//[84]
 
        switch (yourShape.hand()) {//[85]
            case Shape.GU://[86]
                if (myShape.hand() == Shape.CYOKI)//[87]
                    return Result.RESULT_WIN;//[88]
                break;//[89]
            case Shape.CYOKI://[90]
                if (myShape.hand() == Shape.PA)//[91]
                    return Result.RESULT_WIN;//[92]
                break;//[93]
            case Shape.PA://[94]
                if (myShape.hand() == Shape.GU)//[95]
                    return Result.RESULT_WIN;//[96]
                break;//[97]
            default://[98]
                break;//[99]
        }
        return Result.RESULT_FALSE;//[100]
    }
}